sudo: false
dist: xenial
language: python
python:
- '3.6'
- '3.7'
git:
  depth: false
cache: pip
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda env create -n test-environment -f environment.yml python=$TRAVIS_PYTHON_VERSION
- source activate test-environment
- pip install -r requirements.txt
- pip install pytest
- pip install -e .
script:
- pytest -v -s
deploy:
  provider: pypi
  user: jshenk
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    branch: master
  password:
    secure: E8GDZnbonlaYFyneYEG+h2pUBYUJK8RQIVpMlhY0yMBdtaxGcE0JN/XqKMG/W1076MqVHtCKFA05H34l5r8B/uy2p+u4sv1S4rhcLi6FrMqci5M0OO+dkPnFnlLX8DsENgPUFXsCylom+zKQwT6rgn80zAUm7dJALlF2U6Qa3/izanwBKYPInvdtkdnEqpDOcancWkFE2GYmT3V2VNSOGUv9kjbIjYcYu8LbEibleXkhpKqYQ0RYA9mg/ooscFIm3+Dw2KNxOx6CC1L9FbevUW65KWpF5OH05dU3uMPPvWe/sT0mbPdoOpUDAXhMu5MgW/yH4mCkBoH7bZ3eKYNgdn5ZCwuKiG4W62SYQO7BBSh/56YC5OVKipj+eRv3qdvDU9C3KUovcnabI0bi81TrAX8axRNFmvDIjkH2nH9laHMux+M6AhxbcaGAT1waN+qWg5RI6RYUVRTZqaR/YTXbEMDn0PQ16ULVxbz+qPcae9hYGjvUnXvXADw0D7gBr9V3tPMn0XZLzja64K2zkO2ZrPyo9LmoJrH0PRX4WdXg4PeMqnVsOzo5bmozJEsYpRdml+T6TJJOLeKQFqkxcbI5ETHynnUaq6D0/2GnyAlPqHczDps9Y34Cx5B7QlvhRqj7sUDNoqmikkEFnJy8ZuVNRDpt/nJMaAUyvuO6C7xFw+c=
